---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# .. Copyright (C) 2014-2019 Maciej Delmanowski <drybjed@gmail.com>
# .. Copyright (C) 2015-2019 DebOps <https://debops.org/>
# .. SPDX-License-Identifier: GPL-3.0-only

# .. _samba__ref_defaults:

# debops.samba default variables
# ==============================

# .. contents:: Sections
#    :local:
#
# .. include:: ../../../../includes/global.rst


# Packages and installation [[[
# -----------------------------

# .. envvar:: samba__base_packages [[[
#
# List of base packages to install.
# In case you only want to prepare the host for being a Samba client, remove
# the ``samba`` package from the list. This might be required because
# applications like ownCloud depend on the :command:`smbclient` which gets things like
# workgroup from the file :file:`/etc/samba/smb.conf`.
samba__base_packages:
  - 'samba'
  - 'samba-common'
  - 'samba-common-bin'
                                                                   # ]]]
                                                                   # ]]]
# Firewall configuration [[[
# --------------------------

# .. envvar:: samba__allow [[[
#
# Allow access to Samba through firewall for specified networks.
# If this variable is undefined or ``False``, allow access from everywhere.
samba__allow: []

                                                                   # ]]]
# .. envvar:: samba__kernel_modules_load [[[
#
# Use the kernel module
samba__kernel_modules_load: True

                                                                   # ]]]
# .. envvar:: samba__kernel_modules [[[
#
# Kernel modules to load for optimal operation of Samba.
samba__kernel_modules:
  - 'nf_conntrack_netbios_ns'
                                                                   # ]]]
                                                                   # ]]]
# Global Samba options [[[
# ------------------------

# .. envvar:: samba__workgroup [[[
#
# This controls what workgroup your server will appear to be in when queried by
# clients. Note that this parameter also controls the Domain name used with the::
#
#    samba__security: 'domain'
#
# setting.
samba__workgroup: 'WORKGROUP'

                                                                   # ]]]
# .. envvar:: samba__security [[[
#
# This option affects how clients respond to Samba and is one of the most
# important settings in the :file:`/etc/samba/smb.conf` file.
samba__security: 'user'

                                                                   # ]]]
# .. envvar:: samba__netbios_name [[[
#
# This sets the NetBIOS name by which a Samba server is known. By default it is
# the same as the first component of the host's DNS name. If a machine is a
# browse server or logon server this name (or the first component of the hosts
# DNS name) will be the name that these services are advertised under.
samba__netbios_name: '{{ ansible_hostname }}'

                                                                   # ]]]
# .. envvar:: samba__server_string [[[
#
# This controls what string will show up in the printer comment box in print
# manager and next to the IPC connection in net view. It can be any string that
# you wish to show to your users.
# It also sets what will appear in browse lists next to the machine name.
#
# A ``%v`` will be replaced with the Samba version number.
#
# A ``%h`` will be replaced with the hostname.
samba__server_string: '%h file server'

                                                                   # ]]]
# .. envvar:: samba__service_name [[[
#
# Name of the /etc/init.d/ service script
samba__service_name: 'samba'

                                                                   # ]]]
# .. envvar:: samba__name_resolve_order [[[
#
# Resolve order of Samba.
samba__name_resolve_order: 'lmhosts host wins bcast'

                                                                   # ]]]
# .. envvar:: samba__path [[[
#
# Base directory of home directories and shares.
samba__path: '/srv/samba'

                                                                   # ]]]
# .. envvar:: samba__default_global [[[
#
# Default ``[global]`` configuration.
samba__default_global:

  # Browsing / Identification.
  workgroup: '{{ samba__workgroup }}'
  netbios_name: '{{ samba__netbios_name }}'
  server_string: '{{ samba__server_string }}'

  # Logs / Accounting.
  log_file: '/var/log/samba/log.%m'
  max_log_size: '1000'
  syslog: '0'

  # Authentication.
  security: '{{ samba__security }}'
  encrypt_passwords: 'yes'
  passdb_backend: 'tdbsam'
  unix_password_sync: 'no'
  obey_pam_restrictions: 'yes'
  invalid_users: 'root bin daemon adm sync shutdown halt mail news uucp proxy www-data backup sshd'
  map_to_guest: 'never'
  guest_account: 'nobody'

  # File system / Directories.
  unix_charset: 'UTF8'
  locking: 'yes'
  wide_links: 'no'
  browseable: 'yes'
  create_mask: '0660'
  directory_mask: '0770'
  dont_descend: './lost+found'
  use_sendfile: 'yes'
  hide_unreadable: 'yes'
  hide_files: '/.*/lost+found/'

  # Networking / Connections.
  socket_options: 'TCP_NODELAY'
  deadtime: '10'
  wins_support: 'no'
  dns_proxy: 'no'
  name_resolve_order: '{{ samba__name_resolve_order }}'

  # Disable printing by default.
  printing: 'bsd'
  load_printers: 'no'
  printcap_name: '/dev/null'
  show_add_printer_wizard: 'no'
  disable_spoolss: 'yes'

                                                                   # ]]]
# .. envvar:: samba__default_ldap [[[
#
# LDAP ``[global`` configuration.
samba__default_ldap:
  domain_logons: 'yes'
  passdb_backend: 'ldapsam:{{ samba__ldap_passdb_backend }}'
  ldap_suffix: '{{ samba__ldap_base_dn | join(",") }}'
  ldap_user_suffix: '{{ samba__ldap_people_rdn }}'
  ldap_group_suffix: '{{ samba__ldap_groups_rdn }}'
  ldap_machine_suffix: '{{ samba__ldap_machines_rdn }}'
  ldap_admin_dn: '{{ samba__ldap_binddn }}'
  ldap_ssl: 'start tls'
  # If setting password via Samba, only update the LDAP password
  # The smbk5pwd overlay will update the LM and NT password hashes
  ldap_passwd_sync: 'only'
                                                                   # ]]]
# .. envvar:: samba__global [[[
#
# Which hash variable is used to configure the ``[global]`` section in
# :file:`/etc/samba/smb.conf`.
samba__global: '{{ samba__default_global
                   | combine( samba__default_ldap if (samba__ldap_enabled) else {}) }}'

                                                                   # ]]]
# .. envvar:: samba__global_custom [[[
#
# You can specify additional options in a separate hash.
samba__global_custom: {}
                                                                   # ]]]
                                                                   # ]]]
# Home directories [[[
# --------------------

# .. envvar:: samba__homes_path [[[
#
# Location of home directories on the Samba server.
samba__homes_path: '{{ samba__path }}/home'

                                                                   # ]]]
# .. envvar:: samba__homes [[[
#
# Which hash variable is used to configure the ``[homes]`` section in
# :file:`/etc/samba/smb.conf`.
samba__homes: '{{ samba__default_homes }}'

                                                                   # ]]]
# .. envvar:: samba__default_homes [[[
#
# Default ``[homes]`` section.
samba__default_homes:
  path: '{{ samba__homes_path }}/%S'
  comment: 'Home Directory'
  browseable: 'no'
  read_only: 'no'
  create_mask: '0600'
  directory_mask: '0700'
  valid_users: '%S'
  guest_ok: 'no'
  root_preexec: '/usr/local/sbin/samba-homedir.sh %S'
                                                                   # ]]]
                                                                   # ]]]
# Network shares [[[
# ------------------

# .. envvar:: samba__shares_path [[[
#
# Base directory for shares.
samba__shares_path: '{{ samba__path }}/shares'

                                                                   # ]]]
# .. envvar:: samba__shares [[[
#
# Which hash of hashes is used to configure shares in
# :file:`/etc/samba/smb.conf`.
samba__shares: '{{ samba__default_shares }}'

                                                                   # ]]]
# .. envvar:: samba__default_shares [[[
#
# Hash of hashes of default shares.
samba__default_shares:

  'Public Files':
    path: '{{ samba__shares_path }}/public'
    comment: 'Public Files'
    read_only: 'yes'
    guest_ok: 'yes'
                                                                   # ]]]
                                                                   # ]]]
# LDAP configuration [[[
# ----------------------

# .. envvar:: samba__ldap_enabled [[[
#
# Enable or disable LDAP integration in Samba.
samba__ldap_enabled: '{{ ansible_local.ldap.enabled
                         if (ansible_local|d() and ansible_local.ldap|d() and
                             ansible_local.ldap.enabled is defined)
                         else False }}'

                                                                   # ]]]
# .. envvar:: samba__domain_sid [[[
#
# The security identifier to use the the domain.
samba__domain_sid: "S-1-5-21-{{ lookup('password', secret + '/samba/' +
                                samba__workgroup + '/SID/subauthority1
                                length=10 chars=digits')
                                }}-{{
                                lookup('password', secret + '/samba/' +
                                samba__workgroup + '/SID/subauthority2
                                length=10 chars=digits')
                                }}-{{
                                lookup('password', secret + '/samba/' +
                                samba__workgroup + '/SID/subauthority3
                                length=10 chars=digits') }}"
                                                                   # ]]]

# .. envvar:: samba__ldap_hosts [[[
#
# List of the FQDN addresses of the LDAP directory servers which should be used
# by samba.
samba__ldap_hosts: '{{ ansible_local.ldap.hosts|d([]) }}'

                                                                   # ]]]
# .. envvar:: samba__ldap_passdb_backend [[[
#
# The passdb backend configuration to use for LDAP backed Samba.
samba__ldap_passdb_backend: '"ldap://{{ samba__ldap_hosts | join(" ldap://") }}"'

                                                                   # ]]]
# .. envvar:: samba__ldap_port [[[
#
# The TCP port to use to connect to the LDAP directory.
samba__ldap_port: '{{ ansible_local.ldap.port|d("389") }}'

                                                                   # ]]]
# .. envvar:: samba__ldap_use_tls [[[
#
# Enable or disable support for STARTTLS extension while connecting to the LDAP
# directory.
samba__ldap_use_tls: '{{ ansible_local.ldap.start_tls|d(True) }}'

                                                                   # ]]]
# .. envvar:: samba__ldap_base_dn [[[
#
# The Base Distinguished Name of the LDAP directory, defined as a YAML list.
samba__ldap_base_dn: '{{ ansible_local.ldap.base_dn|d([]) }}'

                                                                   # ]]]
# .. envvar:: samba__ldap_device_dn [[[
#
# The Distinguished Name of the current host LDAP object, defined as a YAML
# list. It will be used as a base for the samba application account LDAP
# object. If the list is empty, the role will not create the account LDAP
# object automatically.
samba__ldap_device_dn: '{{ ansible_local.ldap.device_dn|d([]) }}'

                                                                   # ]]]
# .. envvar:: samba__ldap_self_rdn [[[
#
# The Relative Distinguished Name of the account LDAP object used by the
# samba application to access the LDAP directory.
samba__ldap_self_rdn: 'uid=samba'

                                                                   # ]]]
# .. envvar:: samba__ldap_self_object_classes [[[
#
# List of the LDAP object classes which will be used to create the LDAP object
# used by the samba application to access the LDAP directory.
samba__ldap_self_object_classes: [ 'account', 'simpleSecurityObject' ]

                                                                   # ]]]
# .. envvar:: samba__ldap_self_attributes [[[
#
# YAML dictionary that defines the attributes of the LDAP object used by the
# samba application to access the LDAP directory.
samba__ldap_self_attributes:
  uid: '{{ samba__ldap_self_rdn.split("=")[1] }}'
  userPassword: '{{ samba__ldap_bindpw }}'
  host: '{{ [ ansible_fqdn, ansible_hostname ] | unique }}'
  description: 'Account used by the "samba" application to access the LDAP directory'

                                                                   # ]]]
# .. envvar:: samba__ldap_binddn [[[
#
# The Distinguished Name of the account LDAP object used by the
# samba application to bind to the LDAP directory.
samba__ldap_binddn: '{{ ([ samba__ldap_self_rdn ] + samba__ldap_device_dn) | join(",") }}'

                                                                   # ]]]
# .. envvar:: samba__ldap_bindpw [[[
#
# The password stored in the account LDAP object used by the samba
# application to bind to the LDAP directory.
samba__ldap_bindpw: '{{ lookup("password", secret + "/ldap/credentials/"
                                   + samba__ldap_binddn | to_uuid + ".password length=32") }}'

                                                                   # ]]]
# .. envvar:: samba__ldap_people_rdn [[[
#
# The Relative Distinguished Name of the people subtree which contains personal
# LDAP entries.
samba__ldap_people_rdn: '{{ ansible_local.ldap.people_rdn|d([]) }}'

                                                                   # ]]]
# .. envvar:: samba__ldap_people_dn [[[
#
# The Distinguished Name of the people subtree.
samba__ldap_people_dn: '{{ [ samba__ldap_people_rdn ]
                               + samba__ldap_base_dn }}'

                                                                   # ]]]
# .. envvar:: samba__ldap_machines_rdn [[[
#
# The Relative Distinguished Name of the machines subtree which contains machine
# LDAP entries.
samba__ldap_machines_rdn: '{{ ansible_local.ldap.machines_rdn|d([]) }}'

                                                                   # ]]]
# .. envvar:: samba__ldap_machines_dn [[[
#
# The Distinguished Name of the machines subtree.
samba__ldap_machines_dn: '{{ [ samba__ldap_machines_rdn ]
                               + samba__ldap_base_dn }}'

                                                                   # ]]]
# .. envvar:: samba__ldap_groups_rdn [[[
#
# The Relative Distinguished Name of the groups subtree which contains group
# LDAP entries.
samba__ldap_groups_rdn: '{{ ansible_local.ldap.groups_rdn|d([]) }}'

                                                                   # ]]]
# .. envvar:: samba__ldap_groups_dn [[[
#
# The Distinguished Name of the groups subtree.
samba__ldap_groups_dn: '{{ [ samba__ldap_groups_rdn ]
                               + samba__ldap_base_dn }}'

                                                                   # ]]]

# .. envvar:: samba__ldap_domain_rdn [[[
#
# The Relative Distinguished Name of the domain LDAP object.
samba__ldap_domain_rdn: '{{ "sambaDomainName=" + samba__workgroup }}'

                                                                   # ]]]
# .. envvar:: samba__ldap_domain_object_classes [[[
#
# List of the LDAP object classes which will be used to create the LDAP object
# used by the samba application to access the LDAP directory.
samba__ldap_domain_object_classes: [ 'sambaDomain' ]

                                                                   # ]]]
# .. envvar:: samba__ldap_domain_attributes [[[
#
# YAML dictionary that defines the attributes of the LDAP object used by the
# samba application to access the LDAP directory.
samba__ldap_domain_attributes:
  sambaDomainName: '{{ samba__ldap_domain_rdn.split("=")[1] }}'
  sambaSID: '{{ samba__domain_sid }}'
  sambaPwdHistoryLength: 0
  sambaMaxPwdAge: '-1'
  sambaMinPwdAge: 0

                                                                   # ]]]
# .. envvar:: samba__ldap_binddn [[[
#
# The Distinguished Name of the account LDAP object used by the
# samba application to bind to the LDAP directory.
samba__ldap_domain_dn: '{{ ([ samba__ldap_domain_rdn, "ou=Domains" ]
                            + samba__ldap_base_dn) | join(",") }}'

                                                                   # ]]]
# .. envvar:: samba__ferm__dependent_rules [[[
#
# Configuration for :command:`iptables` firewall managed by :program:`ferm`.
samba__ferm__dependent_rules:

  - type: 'accept'
    protocol: [ 'udp' ]
    dport: [ 'netbios-ns', 'netbios-dgm' ]
    saddr: '{{ samba__allow }}'
    accept_any: True
    filename: 'samba__dependency_accept_udp'
    delete: '{{ "samba" not in samba__base_packages }}'
    weight: '50'

  - type: 'accept'
    protocol: [ 'tcp' ]
    dport: [ 'netbios-ssn', 'microsoft-ds' ]
    saddr: '{{ samba__allow }}'
    accept_any: True
    filename: 'samba__dependency_accept_tcp'
    delete: '{{ "samba" not in samba__base_packages }}'
    weight: '50'

                                                                   # ]]]
# .. envvar:: samba__ldap__dependent_tasks [[[
#
# Configuration for the :ref:`debops.ldap` Ansible role.
samba__ldap__dependent_tasks:

  - name: 'Create samba account for {{ samba__ldap_device_dn | join(",") }}'
    dn: '{{ samba__ldap_binddn }}'
    objectClass: '{{ samba__ldap_self_object_classes }}'
    attributes: '{{ samba__ldap_self_attributes }}'
    no_log: True
    state: '{{ "present"
               if (samba__ldap_enabled)
               else "ignore" }}'

  - name: 'Enable reading NT and LM password hashes by samba account of {{ samba__ldap_device_dn | join(",") }}'
    dn: '{{ ([ "cn=Samba Server Account", "ou=Roles" ] + samba__ldap_base_dn) | join(",") }}'
    attributes:
      roleOccupant: '{{ samba__ldap_binddn }}'
    state: '{{ "present"
               if (samba__ldap_enabled)
               else "ignore" }}'

  - name: 'Create samba domain for {{ samba__ldap_domain_dn }}'
    dn: '{{ samba__ldap_domain_dn }}'
    objectClass: '{{ samba__ldap_domain_object_classes }}'
    attributes: '{{ samba__ldap_domain_attributes }}'
    state: '{{ "present"
               if (samba__ldap_enabled)
               else "ignore" }}'

                                                                   # ]]]
